version: '3.8'
services:
  db:
    image: postgres:16
    container_name: expense-db
    environment:
      POSTGRES_DB: expenses_db
      POSTGRES_USER: expenses
      POSTGRES_PASSWORD: expenses
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
